export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}
export enum Qualification {
  PHD = 'PHD',
  MASTERS = 'MASTERS',
  MASTERS_OF_EDUCATION = 'MASTERS_OF_EDUCATION',
  MBA = 'MBA',
  BACHELORS = 'BACHELORS',
  BACHELORS_OF_EDUCATION = 'BACHELORS_OF_EDUCATION',
  ASSOCIATE_DEGREE = 'ASSOCIATE_DEGREE',
  DIPLOMA = 'DIPLOMA',
  POSTGRADUATE_DIPLOMA = 'POSTGRADUATE_DIPLOMA',
  HIGHER_NATIONAL_DIPLOMA = 'HIGHER_NATIONAL_DIPLOMA',
  CERTIFICATE = 'CERTIFICATE',
  TEACHING_CERTIFICATE = 'TEACHING_CERTIFICATE',
  RESEARCH_FELLOW = 'RESEARCH_FELLOW',
  POSTDOCTORATE = 'POSTDOCTORATE',
  OTHER = 'OTHER',
}

export enum Designation {
  PROFESSOR = 'PROFESSOR',
  ASSOCIATE_PROFESSOR = 'ASSOCIATE_PROFESSOR',
  ASSISTANT_PROFESSOR = 'ASSISTANT_PROFESSOR',
  LECTURER = 'LECTURER',
  SENIOR_LECTURER = 'SENIOR_LECTURER',
  ADJUNCT_PROFESSOR = 'ADJUNCT_PROFESSOR',
  VISITING_PROFESSOR = 'VISITING_PROFESSOR',
  TEACHING_ASSISTANT = 'TEACHING_ASSISTANT',
  INSTRUCTOR = 'INSTRUCTOR',
  SENIOR_INSTRUCTOR = 'SENIOR_INSTRUCTOR',
  RESEARCH_FELLOW = 'RESEARCH_FELLOW',
  POSTDOCTORAL_RESEARCHER = 'POSTDOCTORAL_RESEARCHER',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  DEAN = 'DEAN',
  ACADEMIC_COORDINATOR = 'ACADEMIC_COORDINATOR',
}
